VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Declarations"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

'Project
Public NroPrj As Long
Public DscPrj As String
Public ModRotPrj As String
Public CmdSQLPrj As String

'Visual Basic
Public DscVB As String
Public NroVB As Long

Public ErrExiste As Boolean
