IF object_id('dbo.SubGrupos') IS NOT NULL
	DROP TABLE dbo.Marcas 
GO

CREATE TABLE dbo.SubGrupos (
	Empresa CHAR(2) NOT NULL,
	Codigo NUMERIC(10) NOT NULL,
	Descricao VARCHAR(40) NOT NULL,
	Abreviatura VARCHAR(20) NOT NULL,
	Situacao CHAR(1) NOT NULL
)

ALTER TABLE dbo.SubGrupos ADD CONSTRAINT PK_SUBGRUPOS PRIMARY KEY (Empresa, Codigo)
ALTER TABLE dbo.SubGrupos ADD CONSTRAINT CK_SUBGRUPOS_SITUACAO CHECK (Situacao IN ('1', '2'))
GO