IF object_id('dbo.LogAcesso') IS NOT NULL
	DROP TABLE dbo.LogAcesso
GO

CREATE TABLE dbo.LogAcesso (
	Empresa CHAR(2) NOT NULL,
	Codigo NUMERIC(10) NOT NULL IDENTITY,
	CodUsuario NUMERIC(10) NOT NULL,
	DtHr DATETIME NOT NULL,
	Processo CHAR(1) NOT NULL
)

ALTER TABLE dbo.LogAcesso ADD CONSTRAINT PK_LOGACESSO PRIMARY KEY (Empresa, Codigo)
ALTER TABLE dbo.LogAcesso ADD CONSTRAINT FK_LOGACESSO_EMPRESAS FOREIGN KEY (Empresa) REFERENCES dbo.Empresas (Codigo)
ALTER TABLE dbo.LogAcesso ADD CONSTRAINT CK_LOGACESSO_PROCESSO CHECK (Processo IN ('E','S'))
GO
 