CREATE TABLE Empresas (
	Codigo CHAR(2) NOT NULL,
	RazaoSocial VARCHAR(80) NOT NULL,
	CPFCNPJ CHAR(14) NOT NULL,
	DataFundacao DATE NOT NULL,
	Situacao CHAR(1) NOT NULL
)
ALTER TABLE Empresas ADD CONSTRAINT PK_EMPRESAS PRIMARY KEY (Codigo)
ALTER TABLE Empresas ADD CONSTRAINT CK_EMPRESAS_SITUACAO CHECK (Situacao IN ('S', 'N'))
GO