IF OBJECT_ID('LogAcesso') IS NOT NULL
	DROP TABLE LogAcesso;
GO

CREATE TABLE LogAcesso (
	Empresa CHAR(2) NOT NULL,
	CodUsuario NUMERIC(10) NOT NULL,
	DtHr DATETIME NOT NULL,
	TpAcesso CHAR(1)
)
ALTER TABLE LogAcesso ADD CONSTRAINT FK_LOGACESSO_EMPRESA FOREIGN KEY (Empresa) REFERENCES Empresas (Codigo)
ALTER TABLE LogAcesso ADD CONSTRAINT FK_LOGACESSO_USUARIO FOREIGN KEY (Empresa, CodUsuario) REFERENCES Usuarios (Empresa, Codigo)
GO