CREATE TABLE Usuarios (
	Empresa CHAR(2) NOT NULL,
	Codigo NUMERIC(10) NOT NULL,
	Nome VARCHAR(40) NOT NULL,
	Usuario VARCHAR(40) NOT NULL,
	Senha VARCHAR(40) NOT NULL,
	NivelAcesso CHAR(1) NOT NULL,
	Situacao CHAR(1) NOT NULL
)
ALTER TABLE Usuarios ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (Empresa, Codigo)
ALTER TABLE Usuarios ADD CONSTRAINT CK_USUARIOS_SITUACAO CHECK (Situacao IN ('S', 'N'))
ALTER TABLE Usuarios ADD CONSTRAINT CK_USUARIOS_NIVELACESSO CHECK (NivelAcesso IN (1, 2)) 
-- 1 = Administrador, 2 = Usuario